class DeleteFromDatabaseNotUsedTables < ActiveRecord::Migration
  def up
    drop_table :activities
    drop_table :acitivity_reminders
    drop_table :ages
    drop_table :album_photos
    drop_table :albums
    drop_table :analytics
    drop_table :attached_files
    drop_table :attachednotes
    drop_table :blog_comments
    drop_table :bookings
    drop_table :bride_images
    drop_table :brides
    drop_table :budget_distribution_types
    drop_table :budget_invitation_types
    drop_table :buget_invitee_counts
    drop_table :buget_ranges
    drop_table :buget_slots
    drop_table :buget_types
    drop_table :bugets
    drop_table :campaign_anecdote_images
    drop_table :campaign_anecdotes
    drop_table :campaign_gallery_item_images
    drop_table :campaign_gallery_items
    drop_table :campaign_user_account_infos
    drop_table :ceremony_day_hours
    drop_table :ceremony_days
    drop_table :ceremony_images
    drop_table :ceremony_types
    drop_table :ceremonies
    drop_table :challenge_activity_types
    drop_table :challenge_activities
    drop_table :challenges
    drop_table :color_types
    drop_table :contest_travelite_votes
    drop_table :contest_travelites
    drop_table :contest_vote_counts
    drop_table :contract_states
    drop_table :contract_types
    drop_table :contracts
    drop_table :conversations
    drop_table :countries
    drop_table :couples
    drop_table :cua_votes
    drop_table :days
    drop_table :default_activities
    drop_table :default_invitee_groups
    drop_table :dress_requests
    drop_table :events
    drop_table :expenses
    drop_table :feedbacks
    drop_table :genders
    drop_table :gift_card_codes
    drop_table :gift_card_statuses
    drop_table :gift_cards
    drop_table :groom_images
    drop_table :grooms
    drop_table :important_dates
    drop_table :industry_category_types
    drop_table :industry_categories
    drop_table :invitations
    drop_table :invitee_groups
    drop_table :invitee_hosts
    drop_table :invitee_roles
    drop_table :invitees
    drop_table :invoice_months
    drop_table :invoices
    drop_table :languages
    drop_table :lead_contacts
    drop_table :leads
    drop_table :matri_drea_ics
    drop_table :matri_reminders
    drop_table :matrisheets
    drop_table :messages
    drop_table :no_more_bookings
    drop_table :opportunity_images
    drop_table :opportunities
    drop_table :pack_promotions
    drop_table :payer_types
    drop_table :payers
    drop_table :persons
    drop_table :product_budgets
    drop_table :product_faqs
    drop_table :product_images
    drop_table :product_types
    drop_table :products
    drop_table :reference_requests
    drop_table :rent_types
    drop_table :reserved_dates
    drop_table :reviews
    drop_table :rocks
    drop_table :schedule_day_types
    drop_table :schedule_days
    drop_table :service_budgets
    drop_table :service_faqs
    drop_table :service_images
    drop_table :services
    drop_table :star_ratings
    drop_table :statuses
    drop_table :sub_industry_categories
    drop_table :tentative_budgets
    drop_table :tips
    drop_table :trading_houses
    drop_table :user_contest_selection
    drop_table :videos
    drop_table :view_count_types
    drop_table :webpage_contact_states
    drop_table :wed_benchamrks
    drop_table :wedding_planner_quotes
  end

  def down
  end
end
